import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth';
import LogIn from '@/components/LogIn';
import Providers from '@/components/Providers';
import { authOptions } from './api/auth/[...nextauth]/route';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

const session = await  getServerSession(authOptions);


  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers session={session}>
     {session ? <>{children}</> : <> <LogIn /> </>}
  </Providers>
      </body>
    </html>
  )
}
